// LogClient monitors a log file generated by Unreal Engine (DevLog_YYYY-MM-DD.txt)
// for lines containing "ERROR" and saves them to a separate file.
//
// It connects to a LogServer to broadcast these errors in real-time,
// using Protobuf and length-prefixed TCP for communication.
//
// Features to add:
//   - Input arguments for filenames, polling rate, or log level to monitor.
//   - More flexible log parsing (e.g., support for different log formats or levels)
//   - More robust error handling (e.g., file access issues).
//   - Save to structured format (e.g., JSON) for easier analysis.
//
// Note: This is a basic implementation that needs adjustments based on the specific log format and requirements.
package main

import (
	"bufio"
	"context"
	"encoding/binary"
	"fmt"
	"io"
	"log"
	"net"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"

	"playground/LogClient/pb"

	"google.golang.org/protobuf/proto"
)

var (
	// Keep track of the total number of unique errors found across all log entries.
	nrOfErrorsTotal int
	// Keep track of how many errors were already present in the saved file when we started.
	nrOfExistingErrors int
	// seenErrors keeps track of unique error messages in memory for fast lookup.
	// Using a map[string]bool provides O(1) performance compared to O(n) for file scanning.
	seenErrors = make(map[string]bool)
	// Filename for the saved errors, generated based on today's date.
	savedErrorsFilename string
	// serverAddress stores the host and port for the LogServer.
	serverAddress string
	// connection to the LogServer
	serverConn net.Conn
	// Protects serverConn from concurrent read/write and reconnection attempts.
	serverConnMutex sync.Mutex
	// How often we check for new log entries when we reach the end of the file, in milliseconds.
	pollingRate = 2000
	// Last attempt to reconnect to the server.
	lastReconnectAttempt time.Time
)

const (
	// DefaultPort is the standard port for gRPC and related Protobuf services.
	DefaultPort = ":50051"
)

/*
 * Our custom logs are generated from Unreal in the format of "DevLog_<date>.txt"
 * Each log line is expected to contain a timestamp, log level, and message.
 */
func main() {
	fmt.Println("🤖 Log Monitor is running...")

	// Target address for the LogServer
	serverAddress = "localhost" + DefaultPort

	// Connect to LogServer
	connectToServer(serverAddress)

	// Generate filename based on today's date (DevLog_YYYY-MM-DD.txt)
	//TODO This should be an optional input parameter.
	today := time.Now().Format("2006-01-02")
	logFilename := fmt.Sprintf("DevLog_%s.txt", today)
	savedErrorsFilename = fmt.Sprintf("SavedErrors_%s.txt", today)

	// Save the file handle for the saved errors file, so we can keep it open and avoid reopening it for every write.
	savedErrorsFile, err := os.OpenFile(savedErrorsFilename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Printf("Error opening file %s: %v", savedErrorsFilename, err)
		return
	}
	defer savedErrorsFile.Close()

	// Pre-populate the map with any errors already in the saved file
	loadExistingErrors()

	// Create a context that is cancelled when we receive an interrupt signal
	// We want to be able to print stuff when we are done, rather than just aborting the application immediately.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	fmt.Printf("👀 Monitoring %s for 'ERROR' level logs...\n", logFilename)

	// Open the logfile
	logfile, err := os.Open(logFilename)
	if err != nil {
		log.Fatal(err)
	}
	defer logfile.Close() // Ensure the file is closed when current function is done

	// Save existing lines from the beginning of the log file.
	//TODO Can move to separate function?
	logfileReader := bufio.NewReader(logfile)
	for {
		line, err := logfileReader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				// We've reached the end of existing content
				break
			}
			// If any other error occurs, we should log it.
			log.Printf("Error reading existing lines: %v", err)
			shutdown(1)
			return
		}
		saveErrorLine(line, savedErrorsFile)
	}

	// Simple "tail -f" implementation loop,
	// continuously checking for new lines and processing them as they come in.
	for {
		select {
		case <-ctx.Done():
			shutdown(0)
			return
		default:
			// Check if we need to reconnect to the server (every 10 seconds if disconnected)
			serverConnMutex.Lock()
			if serverConn == nil && time.Since(lastReconnectAttempt) > 10*time.Second {
				lastReconnectAttempt = time.Now()
				serverConnMutex.Unlock()
				// This works because of connectToServer running in its own goroutine.
				// If we called connectToServer without the go keyword, the application would hang forever because
				// the function would be waiting for a lock that is held by its own caller.
				go connectToServer(serverAddress)
			} else {
				serverConnMutex.Unlock()
			}

			line, err := logfileReader.ReadString('\n')
			if err != nil {
				if err == io.EOF {
					// Wait for new data
					fmt.Printf("⏳ No new entries yet, sleeping for a bit...\n")
					time.Sleep(time.Duration(pollingRate) * time.Millisecond)
					continue
				}
				// The err was not the expected EOF, so we should log it and exit.
				log.Printf("Error when reading file: %v", err)
				shutdown(1)
				return
			}
			// Save the log line
			saveErrorLine(line, savedErrorsFile)
		}
	}
}

/*
os.O_APPEND: New data will be written to the end of the file instead of overwriting existing content.
os.O_CREATE: If the file doesn't exist, Go will create it. Without this, the function would return an error if the file was missing.
os.O_WRONLY: Opens the file for Writing Only. (Other options are `O_RDONLY` or `O_RDWR`).

0644 (Permissions)
This is a standard Unix octal notation for file permissions used when a new file is created:

	6 (Owner): Read + Write = 4 (Read) + 2 (Write) = 6
	4 (Group): Read-only
	4 (Others): Read-only

On Windows, Go maps these as closely as possible to Windows attributes (e.g., setting or clearing the "Read-only" attribute), but `0644` is the "standard" convention for text files that anyone can read but only the owner can change.
*/
// saveErrorLine checks the provided line for "ERROR" content and appends it to the
// specified file if it is a new unique entry.
//
// Logic:
//  1. Trims whitespace and skips empty lines.
//  2. If the line contains "ERROR", it checks the 'seenErrors' map for duplicates.
//  3. Writes new unique errors to the file and updates the global error counters.
//  4. Attempts to send the error to the LogServer if a connection is active.
func saveErrorLine(line string, file *os.File) {
	line = strings.TrimSpace(line)
	if line == "" {
		return // skip empty lines
	}

	if strings.Contains(strings.ToUpper(line), "ERROR") {
		if seenErrors[line] {
			return // Check if we've already seen this error line to avoid duplicates in the saved file
		}

		if _, err := file.WriteString(fmt.Sprintf("%s\n", line)); err != nil {
			log.Printf("Error writing to file %s: %v", savedErrorsFilename, err)
		} else {
			// Update the map after successful write
			seenErrors[line] = true
			fmt.Printf("🚨 NEW ERROR SEEN:   %s\n", line)
			nrOfErrorsTotal++

			// Send to LogServer if connected
			serverConnMutex.Lock()
			if serverConn != nil {
				sendToLogServer(line)
			}
			serverConnMutex.Unlock()
		}
	}
}

// connectToServer attempts to establish a connection to the LogServer at the
// specified address string.
// Logic:
//  1. Locks the serverConnMutex to prevent concurrent connection changes.
//  2. If an old connection exists, it is closed before dialing.
//  3. Updates serverConn if successful, otherwise keeps it as nil.
func connectToServer(address string) {
	serverConnMutex.Lock()
	defer serverConnMutex.Unlock()

	lastReconnectAttempt = time.Now()

	if serverConn != nil {
		serverConn.Close()
		serverConn = nil
	}

	conn, err := net.DialTimeout("tcp", address, 2*time.Second)
	if err != nil {
		log.Printf("⚠️  Connection to LogServer at %s failed: %v", address, err)
		return
	}

	serverConn = conn
	fmt.Printf("✅ Connected to LogServer at %s\n", address)
}

// sendToLogServer marshals the provided message string into a Protobuf entry and
// transmits it to the LogServer.
//
// Logic:
//  1. Creates a pb.LogEntry with an "ERROR" level and current timestamp.
//  2. Marshals the entry and calculates the payload size.
//  3. Sends a 4-byte length prefix (Big-Endian) followed by the binary data.
//  4. On network failure, cleans up the connection and sets serverConn to nil.
func sendToLogServer(message string) {
	logEntry := &pb.LogEntry{
		Level:     "ERROR",
		Timestamp: time.Now().Unix(),
		Message:   message,
	}

	data, err := proto.Marshal(logEntry)
	if err != nil {
		log.Printf("Error marshaling log entry: %v", err)
		return
	}

	// Send the size of the message first (standard way to delimited protobuf messages in TCP)
	// We'll use 4 bytes (uint32) for the length.
	size := uint32(len(data))
	sizeBuf := make([]byte, 4)
	binary.BigEndian.PutUint32(sizeBuf, size)

	// Send length followed by data
	_, err = serverConn.Write(sizeBuf)
	if err != nil {
		log.Printf("Error sending size to server: %v", err)
		serverConn.Close()
		serverConn = nil
		// Trigger a reconnection attempt in a separate goroutine so we don't block
		go connectToServer("localhost" + DefaultPort)
		return
	}

	_, err = serverConn.Write(data)
	if err != nil {
		log.Printf("Error sending log entry to server: %v", err)
		// Set to nil so we don't keep trying and failing
		serverConn.Close()
		serverConn = nil
		// Trigger a reconnection attempt in a separate goroutine so we don't block
		go connectToServer("localhost" + DefaultPort)
		return
	}
}

// loadExistingErrors reads the persistent error file on startup to pre-populate
// the in-memory 'seenErrors' map.
//
// Logic:
//  1. Gracefully handles scenarios where the saved error file does not yet exist.
//  2. Reads the file line by line, updating the deduplication map and error counts.
//  3. Synchronizes the total error count with any existing historic logs.
func loadExistingErrors() {
	file, err := os.Open(savedErrorsFilename)
	if err != nil {
		return // File doesn't exist yet.
	}
	defer file.Close()

	savedErrorsReader := bufio.NewReader(file)
	for {
		line, err := savedErrorsReader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			log.Printf("Error reading %s: %v", savedErrorsFilename, err)
			break
		}

		line = strings.TrimSpace(line)
		if line != "" {
			seenErrors[line] = true
			nrOfExistingErrors++
		}
	}
	fmt.Printf("✅ Loaded %d existing errors from %s\n", nrOfExistingErrors, savedErrorsFilename)
	nrOfErrorsTotal += nrOfExistingErrors // Include existing errors in the total count
}

// shutdown prints the final count of 'ERROR' logs found before exiting using the
// provided exit status code.
//
// Logic:
//  1. Swaps between exit codes to print a relevant status message.
//  2. Displays statistics for existing, new, and total error counts.
func shutdown(code int) {
	switch code {
	case 0:
		fmt.Println("\n✅ LogMonitor is shutting down gracefully.")
	default:
		fmt.Println("\n🛑 LogMonitor is shutting down due to ReadString error.")
	}

	fmt.Printf("Number of 'ERROR' logs already present:  %d\n", nrOfExistingErrors)
	fmt.Printf("Number of new 'ERROR' logs found:        %d\n", nrOfErrorsTotal-nrOfExistingErrors)
	fmt.Printf("Total number of 'ERROR' logs:            %d\n", nrOfErrorsTotal)
}
