/*
 * LogClient.go
 *
 * This Go application monitors a log file generated by Unreal Engine (DevLog_YYYY-MM-DD.txt) for lines containing "ERROR".
 * It saves unique error lines to a separate file (SavedErrors_YYYY-MM-DD.txt) for later review.
 * 		TODO: It needs to send each error to the LogServer, both from the existing lines and the new ones.
 * The application also keeps track of the total number of unique errors found and prints a summary when it is shut down (e.g., via Ctrl+C).
 *
 * Features to add:
 *   - Input arguments for filenames, polling rate, or log level to monitor
 *   - More flexible log parsing (e.g., support for different log formats or levels)
 *   - More robust error handling (e.g., file access issues)
 *   - Save to something else than just copying to another text file, like a database or a structured format (e.g., JSON) for easier analysis later on
 *   - Optionally, a simple web interface to display the errors in real-time, probably not super useful for LogMonitor.
 *
 * Note: This is a very basic implementation and needs adjustments based on the specific log format and requirements.
 */
package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

var (
	// Keep track of the total number of unique errors found across all log entries.
	nrOfErrorsTotal int
	// Keep track of how many errors were already present in the saved file when we started.
	nrOfExistingErrors int
	// seenErrors keeps track of unique error messages in memory for fast lookup.
	// Using a map[string]bool provides O(1) performance compared to O(n) for file scanning.
	seenErrors = make(map[string]bool)
	// Filename for the saved errors, generated based on today's date.
	savedErrorsFilename string
)

/*
 * Our custom logs are generated from Unreal in the format of "DevLog_<date>.txt"
 * Each log line is expected to contain a timestamp, log level, and message.
 */
func main() {
	fmt.Println("🤖 Log Monitor is running...")

	// How often we check for new log entries when we reach the end of the file, in milliseconds.
	//TODO This should be an optional input parameter.
	pollingRate := 500

	// Generate filename based on today's date (DevLog_YYYY-MM-DD.txt)
	//TODO This should be an optional input parameter.
	today := time.Now().Format("2006-01-02")
	logFilename := fmt.Sprintf("DevLog_%s.txt", today)
	savedErrorsFilename = fmt.Sprintf("SavedErrors_%s.txt", today)

	// Save the file handle for the saved errors file, so we can keep it open and avoid reopening it for every write.
	var savedErrorsFile *os.File
	savedErrorsFile, err := os.OpenFile(savedErrorsFilename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Printf("Error opening file %s: %v", savedErrorsFilename, err)
		return
	}
	defer savedErrorsFile.Close()

	// Pre-populate the map with any errors already in the saved file
	loadExistingErrors()

	// Create a context that is cancelled when we receive an interrupt signal
	// We want to be able to print stuff when we are done, rather than just aborting the application immediately.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	fmt.Printf("👀 Monitoring %s for 'ERROR' level logs...\n", logFilename)

	// Open the logfile
	logfile, err := os.Open(logFilename)
	if err != nil {
		log.Fatal(err)
	}
	defer logfile.Close() // Ensure the file is closed when current function is done

	// Save existing lines from the beginning of the log file.
	//TODO Can move to separate function?
	logfileReader := bufio.NewReader(logfile)
	for {
		line, err := logfileReader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				// We've reached the end of existing content
				break
			}
			// If any other error occurs, we should log it.
			log.Printf("Error reading existing lines: %v", err)
			shutdown(1)
			return
		}
		saveErrorLine(line, savedErrorsFile)
	}

	// Simple "tail -f" implementation loop,
	// continuously checking for new lines and processing them as they come in.
	for {
		select {
		case <-ctx.Done():
			shutdown(0)
			return
		default:
			line, err := logfileReader.ReadString('\n')
			if err != nil {
				if err == io.EOF {
					// Wait for new data
					fmt.Printf("⏳ No new entries yet, sleeping for a bit...\n")
					time.Sleep(time.Duration(pollingRate) * time.Millisecond)
					continue
				}
				// The err was not the expected EOF, so we should log it and exit.
				log.Printf("Error when reading file: %v", err)
				shutdown(1)
				return
			}
			// Save the log line
			saveErrorLine(line, savedErrorsFile)
		}
	}
}

/*
 * Print the final count of 'ERROR' logs found before exiting.
 * TODO: This can probably be done nicer.
 */
func shutdown(code int) {
	switch code {
	case 0:
		fmt.Println("\n✅ LogMonitor is shutting down gracefully.")
	default:
		fmt.Println("\n🛑 LogMonitor is shutting down due to ReadString error.")
	}

	fmt.Printf("Number of 'ERROR' logs already present:  %d\n", nrOfExistingErrors)
	fmt.Printf("Number of new 'ERROR' logs found:        %d\n", nrOfErrorsTotal-nrOfExistingErrors)
	fmt.Printf("Total number of 'ERROR' logs:            %d\n", nrOfErrorsTotal)
}

/*
Save lines containing "ERROR" to a separate file (SavedErrors_YYYY-MM-DD.txt) for later review.

os.O_APPEND: New data will be written to the end of the file instead of overwriting existing content.
os.O_CREATE: If the file doesn't exist, Go will create it. Without this, the function would return an error if the file was missing.
os.O_WRONLY: Opens the file for Writing Only. (Other options are `O_RDONLY` or `O_RDWR`).

0644 (Permissions)
This is a standard Unix octal notation for file permissions used when a new file is created:

	6 (Owner): Read + Write = 4 (Read) + 2 (Write) = 6
	4 (Group): Read-only
	4 (Others): Read-only

On Windows, Go maps these as closely as possible to Windows attributes (e.g., setting or clearing the "Read-only" attribute), but `0644` is the "standard" convention for text files that anyone can read but only the owner can change.
*/
func saveErrorLine(line string, file *os.File) {
	line = strings.TrimSpace(line)
	if line == "" {
		return // skip empty lines
	}

	if strings.Contains(strings.ToUpper(line), "ERROR") {
		if seenErrors[line] {
			return // Check if we've already seen this error line to avoid duplicates in the saved file
		}

		if _, err := file.WriteString(fmt.Sprintf("%s\n", line)); err != nil {
			log.Printf("Error writing to file %s: %v", savedErrorsFilename, err)
		} else {
			// Update the map after successful write
			seenErrors[line] = true
			fmt.Printf("🚨 NEW ERROR SEEN:   %s\n", line)
			nrOfErrorsTotal++
		}
	}
}

/*
 * Read the saved errors file on startup to pre-populate the memory map.
 */
func loadExistingErrors() {
	file, err := os.Open(savedErrorsFilename)
	if err != nil {
		return // File doesn't exist yet.
	}
	defer file.Close()

	savedErrorsReader := bufio.NewReader(file)
	for {
		line, err := savedErrorsReader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			log.Printf("Error reading %s: %v", savedErrorsFilename, err)
			break
		}

		line = strings.TrimSpace(line)
		if line != "" {
			seenErrors[line] = true
			nrOfExistingErrors++
		}
	}
	fmt.Printf("✅ Loaded %d existing errors from %s\n", nrOfExistingErrors, savedErrorsFilename)
	nrOfErrorsTotal += nrOfExistingErrors // Include existing errors in the total count
}
